# Site settings
title: If a blogger posts in the forest and doesn't have WiFi...
header-img: img/home-bg.png
email: banddorkfht7@gmail.com
copyright_name: icvlahovic
description: > # this means to ignore newlines until "baseurl:"
  (...will anyone see the post?)
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  icvlahovic
learn_profile: icvlahovic
email_username: banddorkfht7@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
